// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf5rwfqxkJmkcKx1wdpvYxdtJUSCGpRhw',
    appId: '1:1056228257335:web:56ebd89aa17910e18619b2',
    messagingSenderId: '1056228257335',
    projectId: 'match-the-card-547c3',
    authDomain: 'match-the-card-547c3.firebaseapp.com',
    storageBucket: 'match-the-card-547c3.appspot.com',
    measurementId: 'G-2QQW1CYP1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQClZpwUfsl_4NCZtjhdBjZiqCmh2MVC8',
    appId: '1:1056228257335:android:5ee97aba18c50fe18619b2',
    messagingSenderId: '1056228257335',
    projectId: 'match-the-card-547c3',
    storageBucket: 'match-the-card-547c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX-fyIi2E1ZAnVdTIfnBr3kbtwiL7p6rw',
    appId: '1:1056228257335:ios:c1c5b0d0f211209e8619b2',
    messagingSenderId: '1056228257335',
    projectId: 'match-the-card-547c3',
    storageBucket: 'match-the-card-547c3.appspot.com',
    iosBundleId: 'com.example.findTheMatch',
  );
}
